//! Cross-file symbol table for name resolution. Turns numeric ids in event code into readable
//! names. CommonEvent ids map to names plus per-event self-var and input names from the event's
//! own metadata. Global `V[]`/`S[]`/`Sys[]` ids map to names from the System Database. An optional
//! engine glossary maps stock common-event JP names to English.

use std::collections::HashMap;

use serde::Deserialize;
use wolf_formats::common_event::CommonEventsFile;
use wolf_formats::database::Database;

use crate::text::decode_wstr;

/// The engine-default glossary, generated by the readability workflow and embedded.
static GLOSSARY_JSON: &str = include_str!("../data/glossary.json");

/// Engine-text glossary (structural JP to English), generated by the translation workflow.
static ENGINE_GLOSSARY_JSON: &str = include_str!("../data/engine_glossary.json");

/// Load the embedded engine-text glossary (structural name translations).
pub fn load_embedded_engine_glossary() -> HashMap<String, String> {
    #[derive(Deserialize)]
    struct File {
        pairs: Vec<Pair>,
    }
    #[derive(Deserialize)]
    struct Pair {
        jp: String,
        en: String,
    }
    let json = ENGINE_GLOSSARY_JSON.trim_start_matches('\u{feff}');
    match serde_json::from_str::<File>(json) {
        Ok(f) => f.pairs.into_iter().map(|p| (p.jp, p.en)).collect(),
        Err(_) => HashMap::new(),
    }
}

/// Load the embedded engine-default common-event glossary (stock JP name to English).
pub fn load_embedded_glossary() -> Glossary {
    #[derive(Deserialize)]
    struct File {
        entries: Vec<Entry>,
    }
    #[derive(Deserialize)]
    struct Entry {
        jp_name: String,
        en_name: String,
        #[serde(default)]
        args: Vec<String>,
    }
    let json = GLOSSARY_JSON.trim_start_matches('\u{feff}');
    match serde_json::from_str::<File>(json) {
        Ok(f) => Glossary::from_pairs(f.entries.into_iter().map(|e| {
            (
                e.jp_name,
                GlossaryEntry {
                    en_name: e.en_name,
                    args: e.args,
                },
            )
        })),
        Err(_) => Glossary::default(),
    }
}

#[derive(Debug, Clone, Default)]
pub struct SymbolTable {
    /// CommonEvent int-id to metadata (name, self-var names, input arg names).
    pub common_events: HashMap<u32, CommonEventInfo>,
    /// Global variable names from the System Database.
    pub globals: GlobalNames,
    /// Databases by kind (UDB/CDB/SDB), each holding type/data/field names.
    pub databases: Vec<DatabaseNames>,
    /// Engine-default function glossary (stock JP name to English).
    pub glossary: Glossary,
    /// Engine-text glossary: structural JP name to English (variable, DB type, field, and
    /// system-row names). Player-facing game text is absent.
    pub engine_text: HashMap<String, String>,
}

#[derive(Debug, Clone, Default)]
pub struct CommonEventInfo {
    pub name: String,
    /// CSelf index to name, from `unknown8`, the per-event self-variable names.
    pub self_vars: HashMap<u32, String>,
    /// Input argument names in order (leading non-empty `unknown3` entries).
    pub inputs: Vec<String>,
}

#[derive(Debug, Clone, Default)]
pub struct GlobalNames {
    /// `V[n]`, normal/global variables ("通常変数名").
    pub normal: HashMap<u32, String>,
    /// `S[n]`, string variables ("文字列変数名").
    pub string: HashMap<u32, String>,
    /// `Sys[n]`, system variables ("システム変数名").
    pub system: HashMap<u32, String>,
}

#[derive(Debug, Clone)]
pub struct DatabaseNames {
    pub kind: String,
    pub types: Vec<TypeNames>,
}

#[derive(Debug, Clone)]
pub struct TypeNames {
    pub name: String,
    pub data: Vec<String>,
    pub fields: Vec<String>,
}

/// Engine-default glossary: stock common-event JP name to English signature.
#[derive(Debug, Clone, Default)]
pub struct Glossary {
    entries: HashMap<String, GlossaryEntry>,
}

#[derive(Debug, Clone)]
pub struct GlossaryEntry {
    pub en_name: String,
    pub args: Vec<String>,
}

impl Glossary {
    pub fn from_pairs(pairs: impl IntoIterator<Item = (String, GlossaryEntry)>) -> Self {
        Glossary {
            entries: pairs.into_iter().collect(),
        }
    }

    pub fn get(&self, jp_name: &str) -> Option<&GlossaryEntry> {
        self.entries.get(jp_name)
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }
}

const NAME_NORMAL: &str = "通常変数名";
const NAME_STRING: &str = "文字列変数名";
const NAME_SYSTEM: &str = "システム変数名";
/// Reserve/spare variable groups (`予備変数1`..`予備変数9`). Each names the normal variables at
/// `V[group*100000 + row]`.
const NAME_SPARE: &str = "予備変数";

impl SymbolTable {
    pub fn new() -> Self {
        SymbolTable::default()
    }

    /// Register CommonEvent metadata (names plus self-var and input names).
    pub fn add_common_events(&mut self, ce: &CommonEventsFile) {
        for ev in &ce.events {
            let name = decode_wstr(&ev.name, ce.utf8);

            // Self-var names: the unknown8 index equals the CSelf index.
            let mut self_vars = HashMap::new();
            for (i, w) in ev.unknown8.iter().enumerate() {
                let n = decode_wstr(w, ce.utf8);
                if !n.is_empty() {
                    self_vars.insert(i as u32, n);
                }
            }

            // Inputs: leading contiguous non-empty unknown3 entries.
            let mut inputs = Vec::new();
            for w in &ev.unknown3 {
                let n = decode_wstr(w, ce.utf8);
                if n.is_empty() {
                    break;
                }
                inputs.push(n);
            }

            self.common_events.insert(
                ev.int_id,
                CommonEventInfo {
                    name,
                    self_vars,
                    inputs,
                },
            );
        }
    }

    /// Register a database's type/data/field names, and for the System Database the global
    /// variable name tables.
    pub fn add_database(&mut self, kind: &str, db: &Database) {
        for t in &db.types {
            let type_name = decode_wstr(&t.name, db.utf8);
            let target = match type_name.as_str() {
                NAME_NORMAL => Some(&mut self.globals.normal),
                NAME_STRING => Some(&mut self.globals.string),
                NAME_SYSTEM => Some(&mut self.globals.system),
                _ => None,
            };
            if let Some(map) = target {
                for (i, d) in t.data.iter().enumerate() {
                    let n = decode_wstr(&d.name, db.utf8);
                    if !n.is_empty() {
                        map.insert(i as u32, n);
                    }
                }
            }

            // Spare/reserve variable groups name V[group*100000 + row].
            if let Some(g) = type_name
                .strip_prefix(NAME_SPARE)
                .and_then(|s| s.parse::<u32>().ok())
                .filter(|g| (1..=9).contains(g))
            {
                let base = g * 100_000;
                for (i, d) in t.data.iter().enumerate() {
                    let n = decode_wstr(&d.name, db.utf8);
                    if !n.is_empty() {
                        self.globals.normal.insert(base + i as u32, n);
                    }
                }
            }
        }

        let types = db
            .types
            .iter()
            .map(|t| TypeNames {
                name: decode_wstr(&t.name, db.utf8),
                data: t
                    .data
                    .iter()
                    .map(|d| decode_wstr(&d.name, db.utf8))
                    .collect(),
                fields: t
                    .fields
                    .iter()
                    .map(|f| decode_wstr(&f.name, db.utf8))
                    .collect(),
            })
            .collect();
        self.databases.push(DatabaseNames {
            kind: kind.to_string(),
            types,
        });
    }

    pub fn set_glossary(&mut self, glossary: Glossary) {
        self.glossary = glossary;
    }

    pub fn set_engine_text(&mut self, engine_text: HashMap<String, String>) {
        self.engine_text = engine_text;
    }

    /// Translate a structural name to English via the engine-text glossary, or return it
    /// unchanged. Player-facing content is absent from the glossary, so it stays as-is.
    pub fn tr<'a>(&'a self, name: &'a str) -> &'a str {
        self.engine_text
            .get(name)
            .map(String::as_str)
            .unwrap_or(name)
    }

    pub fn common_event(&self, id: u32) -> Option<&CommonEventInfo> {
        self.common_events.get(&id)
    }

    pub fn common_event_name(&self, id: u32) -> Option<&str> {
        self.common_events.get(&id).map(|i| i.name.as_str())
    }

    /// Reverse lookup by exact name (for call-by-name commands).
    pub fn common_event_by_name(&self, name: &str) -> Option<&CommonEventInfo> {
        self.common_events.values().find(|i| i.name == name)
    }

    /// Resolve a database entry (`type name`, `row index`) to its row name, for turning, say,
    /// `ItemId=17` into `ItemId="ポーション"`. Searches all loaded databases.
    pub fn db_entry_name(&self, type_name: &str, row: u32) -> Option<&str> {
        self.db_type(type_name)
            .and_then(|t| t.data.get(row as usize))
            .map(String::as_str)
            .filter(|s| !s.is_empty())
    }

    /// Resolve a database field (column) index to its name within a type.
    pub fn db_field_name(&self, type_name: &str, field: u32) -> Option<&str> {
        self.db_type(type_name)
            .and_then(|t| t.fields.get(field as usize))
            .map(String::as_str)
            .filter(|s| !s.is_empty())
    }

    fn db_type(&self, type_name: &str) -> Option<&TypeNames> {
        self.databases
            .iter()
            .flat_map(|db| &db.types)
            .find(|t| t.name == type_name)
    }

    /// Which database kind (UDB/CDB/SDB) holds a given type.
    pub fn db_kind_of_type(&self, type_name: &str) -> Option<&str> {
        self.databases
            .iter()
            .find(|db| db.types.iter().any(|t| t.name == type_name))
            .map(|db| db.kind.as_str())
    }
}
