'repos':
- 'repo': 'local'
  'hooks':
  - 'id': 'set-defaults'
    'name': 'Set Defaults in rpgmakermvmz.py'
    'entry': 'python -m util.defaults'
    'language': 'python'
    'files': '^modules/rpgmakermvmz.py$'
